%import common._STRING_ESC_INNER
%import common.SIGNED_INT       -> INT
%import common.LETTER           -> C
%import common.DIGIT            -> N
%import common.WS
%ignore WS

// Parenthesis
LP : "("
RP : ")"
DQ : "\""
SQ : "'"

// Tokens
STR : DQ _STRING_ESC_INNER DQ | SQ _STRING_ESC_INNER SQ
DATE.9 : N N N N "-" N N "-" N N
IDENTIFIER : C (C | N | "_")*

// Keywords
TYPE_INT : "int"i
TYPE_CHAR : "char"i
TYPE_DATE : "date"i

EXIT : "exit"i
CREATE : "create"i
DROP : "drop"i
DESC : "desc"i
SHOW : "show"i
TABLE : "table"i
TABLES : "tables"i
RENAME : "rename"i
TRUNCATE : "truncate"i
EXPLAIN : "explain"i
DESCRIBE : "describe"i
TO : "to"i

NOT : "not"i
NULL : "null"i
PRIMARY : "primary"i
FOREIGN : "foreign"i
KEY : "key"i
REFERENCES : "references"i

SELECT : "select"i
FROM : "from"i
WHERE : "where"i
AS : "as"i
IS : "is"i
OR : "or"i
AND : "and"i
INSERT : "insert"i
INTO : "into"i
VALUES : "values"i
DELETE : "delete"i
UPDATE : "update"i
SET : "set"i
JOIN : "join"i
ON : "on"i
ORDER : "order"i
BY : "by"i
ASC : "asc"i
GROUP : "group"i
MAX : "max"i
MIN : "min"i
SUM : "sum"i
COUNT : "count"i
AVG : "avg"i

LESSEQUAL : "<="
LESSTHAN : "<"
GREATEREQUAL : ">="
GREATERTHAN: ">"
NOTEQUAL: "!="
EQUAL: "="

LIMIT: "limit"i
OFFSET: "offset"i


// QUERY
start : command
command : query ";" | exit_query ";"

exit_query : EXIT

query : create_table_query
      | select_query
      | drop_table_query
      | explain_query
      | describe_query
      | desc_query
      | show_tables_query
      | rename_table_query
      | truncate_table_query
      | insert_query
      | delete_query
      | update_query


// CREATE TABLE
create_table_query : CREATE TABLE table_name table_element_list
table_element_list : LP table_element ("," table_element)* RP
table_element : column_definition
              | table_constraint_definition
column_definition : column_name data_type [NOT NULL]
table_constraint_definition : primary_key_constraint
                            | referential_constraint
primary_key_constraint : PRIMARY KEY column_name_list
referential_constraint : FOREIGN KEY column_name_list REFERENCES table_name column_name_list

column_name_list : LP column_name ("," column_name)* RP
data_type : TYPE_INT
          | TYPE_CHAR LP INT RP
          | TYPE_DATE
table_name : IDENTIFIER
column_name : IDENTIFIER
column_ref : [table_name "."] column_name

// table metadata queries
drop_table_query : DROP TABLE table_name
explain_query : EXPLAIN table_name
describe_query : DESCRIBE table_name
desc_query : DESC table_name
show_tables_query : SHOW TABLES
truncate_table_query : TRUNCATE TABLE table_name


// RENAME TABLE
rename_table_query : RENAME TABLE rename_item ("," rename_item)*
rename_item : table_name TO table_name

// INSERT
insert_query : INSERT INTO table_name [column_name_list] VALUES value_list
value_list : LP comparable_value ("," comparable_value)* RP

// DELETE
delete_query : DELETE FROM table_name [where_clause]

// UPDATE
update_query : UPDATE table_name SET set_clause [where_clause]
set_clause : set_item ("," set_item)*
set_item : column_name EQUAL comparable_value

// SELECT
select_query : SELECT select_list from_clause join_clause* [where_clause] [group_by_clause] [order_by_clause] [limit_clause] [offset_clause]
select_list : "*"
            | select_item ("," select_item)*
select_item : aggregate_expr [AS column_name]
            | column_ref [AS column_name]
aggregate_expr : count_func LP count_arg RP
               | aggregate_func LP column_ref RP
count_func : COUNT
count_arg : "*" | column_ref
aggregate_func : MAX | MIN | SUM | AVG

from_clause : FROM table_reference
table_reference : table_name [AS table_name]
join_clause : JOIN table_reference ON join_condition
join_condition : join_column_ref EQUAL join_column_ref
join_column_ref : table_name "." column_name

order_by_clause : ORDER BY order_item ("," order_item)*
order_item : column_ref order_direction
order_direction : ASC | DESC
group_by_clause : GROUP BY column_ref ("," column_ref)*
limit_clause : LIMIT INT
offset_clause : OFFSET INT

// WHERE
where_clause : WHERE boolean_expr
boolean_expr : boolean_term (OR boolean_term)*
boolean_term : boolean_factor (AND boolean_factor)*
boolean_factor : [NOT] boolean_test
boolean_test : predicate
             | parenthesized_boolean_expr
parenthesized_boolean_expr : LP boolean_expr RP
predicate : comparison_predicate
          | null_predicate
comparison_op : LESSEQUAL
              | LESSTHAN
              | GREATERTHAN
              | GREATEREQUAL
              | EQUAL
              | NOTEQUAL
comparison_predicate : comp_operand comparison_op comp_operand
comp_operand : comparable_value
             | column_ref
comparable_value : INT | STR | DATE | NULL
null_predicate : column_ref null_operation
null_operation : IS [NOT] NULL
